### ISSUE TITLE
Databrowser/StripChart causes OutOfMemory error in the web client

### ISSUE THREAD

**Issue by konrad-gajewski** [kasemir/dbwr#23]
Running Strip Chart Plot Widget (display=https://raw.githubusercontent.com/ControlSystemStudio/phoebus/master/app/display/model/src/main/resources/examples/plots_strip.bob) for couple of hours ends with OutOfmemory error. It's expected because in the update method the data is pushed to the plotobj.data array without any limit. However, after adding a line removing the first element of the array after reaching some arbitrary size (I couldn't figure out how much heap space was still available) the widget still was eating up the heap space. The plotobj.data array size was not increasing as reported by this. plotobj.data.length.

```
diff --git a/src/main/webapp/widgets/databrowser.js b/src/main/webapp/widgets/databrowser.js
index 930af71..23b0f50 100644
--- a/src/main/webapp/widgets/databrowser.js
+++ b/src/main/webapp/widgets/databrowser.js
@@ -94,7 +94,11 @@ class DBTrace
         // which can be updated in scroll() or update()
         this.plotobj.data.pop();
         this.plotobj.data.push( [ time, value ] );
-        this.plotobj.data.push( [ time, value ] );        
+        this.plotobj.data.push( [ time, value ] ); 
+       let length = this.plotobj.data.length;
+       console.log("this.plotobj.data.length: " + length);
+       if (length > 180) 
+           this.plotobj.data.shift();
     }
 }
```
The same problem is observed for the databrowser widget.

I was planning to use dbwr for show the "live" plots in the data browsers running in "kiosk" mode (without user interaction) but if this issue is not solved I will have to abandon this idea.

**Comment by kasemir** [comment]
The data browser in the CS-Studio desktop is about 18000 lines of code (plus a plotting library of 11k lines) to combine live and archived data, allow zooming/panning etc.
The web version is only about 500 lines of code (using an existing plotting library). Naturally, it's functionality is much reduced ;-)

https://github.com/ornl-epics/dbwr/commit/17b8cd1921aed6f49bd3d7c1f3460a21391051df just added support for the 'ring size' limit. So it'll now read the live buffer size for each channel from data browser *.plt files. The default is configurable via a         `DEFAULT_PLOT_RING_SIZE` environment variable (5000 if not set), and that limit is also used by the stripchart widget.

So from within the dbwr code we'll now limit the live buffer size as you did in your snippet, but instead of 180 it's honoring those settings.

If you still see out of memory, maybe you can check where that's originating. Might be in the plot library, so then we have to figure out how to have it "update" the plot without growing in memory.

**Comment by konrad-gajewski** [comment]
Thanks a lot. I will try it and report the outcome.

**Comment by konrad-gajewski** [comment]
Limiting the 'ring size' did not fix the problem of growing heap. After some tests I have found out that indeed the plot library was to blame.  I don't know exactly what was wrong but after updating to the latest version of flot library (https://github.com/flot/flot.git, tag v4.2.4) the plots in the browser work fine.
I will make a pull request for the version with the new library.

**Comment by kasemir** [comment]
> plot library ... updating to the latest version .. work fine

Excellent news, thanks!
